// ============================================================
// دمج ملفات الفروع — Power Query (لغة M)
// ------------------------------------------------------------
// المشكلة: 11 فرعاً يرسل ملفاً منفصلاً كل شهر، بترويسات متفاوتة
// وصفوف فارغة وأنواع بيانات غير متسقة. الدمج اليدوي = ساعات
// شهرياً + أخطاء بشرية.
//
// الحل: استعلام واحد يقرأ المجلد كاملاً، يوحّد الأعمدة، ينظّف
// البيانات، ويخرج جدولاً واحداً جاهزاً للنمذجة.
// ============================================================

let
    // 1) قراءة كل ملفات CSV من مجلد الفروع
    المصدر = Folder.Files(FolderPath),

    // 2) استبعاد الملفات المؤقتة والمخفية
    ملفات_صالحة = Table.SelectRows(
        المصدر,
        each not Text.StartsWith([Name], "~$")
             and not Text.StartsWith([Name], ".")
             and Text.EndsWith(Text.Lower([Name]), ".csv")
    ),

    // 3) تحويل كل ملف إلى جدول مع الحفاظ على اسم الملف كمصدر
    مع_المحتوى = Table.AddColumn(
        ملفات_صالحة,
        "البيانات",
        each Csv.Document(
            [Content],
            [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]
        )
    ),

    // 4) ترقية الصف الأول إلى ترويسة داخل كل جدول
    مع_الترويسة = Table.TransformColumns(
        مع_المحتوى,
        {"البيانات", each Table.PromoteHeaders(_, [PromoteAllScalars = true])}
    ),

    // 5) الإبقاء على عمودي اسم الملف والبيانات فقط
    مختصر = Table.SelectColumns(مع_الترويسة, {"Name", "البيانات"}),

    // 6) توسيع الجداول في جدول واحد
    موسّع = Table.ExpandTableColumn(
        مختصر,
        "البيانات",
        {"التاريخ", "الفرع", "الصنف", "الفئة", "الكمية", "سعر الوحدة", "الإجمالي"}
    ),

    // 7) ضبط أنواع البيانات
    بأنواع = Table.TransformColumnTypes(
        موسّع,
        {
            {"التاريخ", type date},
            {"الفرع", type text},
            {"الصنف", type text},
            {"الفئة", type text},
            {"الكمية", Int64.Type},
            {"سعر الوحدة", type number},
            {"الإجمالي", type number}
        }
    ),

    // 8) إزالة الصفوف الفارغة والسالبة
    منظّف = Table.SelectRows(
        بأنواع,
        each [التاريخ] <> null
             and [الفرع] <> null
             and [الكمية] > 0
             and [الإجمالي] >= 0
    ),

    // 9) تشذيب المسافات الزائدة في الحقول النصية
    مشذّب = Table.TransformColumns(
        منظّف,
        {
            {"الفرع", Text.Trim, type text},
            {"الصنف", Text.Trim, type text},
            {"الفئة", Text.Trim, type text}
        }
    ),

    // 10) عمود التحقق — يكشف تعارض الإجمالي مع الكمية × السعر
    مع_تحقق = Table.AddColumn(
        مشذّب,
        "تحقق_الإجمالي",
        each if Number.Abs([الإجمالي] - ([الكمية] * [سعر الوحدة])) < 0.05
             then "سليم"
             else "يحتاج مراجعة",
        type text
    ),

    // 11) حذف عمود اسم الملف بعد انتهاء الحاجة إليه
    نهائي = Table.RemoveColumns(مع_تحقق, {"Name"})
in
    نهائي
